# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [octokit, Mia, Laff, CBD]
patreon: # Replace with a single Patreon username https://www.patreon.com/posts/22854182
open_collective: # Replace with a single Open Collective username https://creativecommons.org HTTP://justinfamily.family.blog
ko_fi: # Replace with a single Ko-fi username Andrew nurx.com
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm install -g babel-node-debug babel-node-debug path/to/script.js
community_bridge: # Replace with a single Community Bridge project-name e.g., https://IANNA.org https://en.wikipedia.org/wiki/Party_platform?wprov=sfti1
liberapay: # Replace with a single Liberapay username Orion 
issuehunt: # Replace with a single IssueHunt username Queenb
otechie: # Replace with a single Otechie username nokia
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://goarmy.com', 'https://chime.com, Https://bounty.com, Https://greengiant.com']
