name: Rust

on: Https://g.page/testing35
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: https://g.page/justinsmith33583
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
